import { parseArgs } from 'node:util';
import process from 'node:process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  SCHEMA_TYPES,
  SchemaType,
  buildPropertyListingPageSchema,
  buildPlaceSchema,
  buildFaqPageSchema,
  buildHowToSchema,
  buildVideoObjectSchema,
  buildOfferSchema,
} from '../generators.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type RouteRule = {
  pattern: string;
  types: SchemaType[];
};

type MatchResult = {
  route: string;
  matched: boolean;
  types: string[];
};

const ROUTES_COLLECTION_FILE = 'seo-routes.json';
const ROUTES_OUTPUT_FILE = 'coverage.json';

export type CoverageArgs = {
  routes?: string;
  output?: string;
  format?: 'md' | 'json' | 'html';
  n8n?: boolean;
  env?: string;
};

export type CoverageResult = {
  matches: MatchResult[];
  coverage: number;
  output?: string;
};

function loadRoutes(filePath: string): RouteRule[] {
  const absolute = path.resolve(filePath);
  if (!fs.existsSync(absolute)) {
    console.error(`Routes file not found: ${absolute}`);
    process.exitCode = 1;
    return [];
  }

  const raw = fs.readFileSync(absolute, 'utf8');
  const parsed = JSON.parse(raw) as Array<Record<string, unknown>>;

  const allowed = Array.from(SCHEMA_TYPES);

  return parsed
    .map((entry) => {
      const pattern = String(entry.pattern ?? entry.route ?? '');
      const rawTypes = Array.isArray(entry.types) ? entry.types : [];

      const normalizedTypes = rawTypes
        .map((item) => String(item))
        .filter((item) => allowed.includes(item as SchemaType)) as SchemaType[];

      if (!pattern || !normalizedTypes.length) return null;
      return { pattern, types: normalizedTypes };
    })
    .filter((rule): rule is RouteRule => rule !== null);
}

function matchRoute(route: string, pattern: string): boolean {
  if (pattern === route) return true;
  const regex = new RegExp(`^${pattern.replace(/\*/g, '.*')}$`);
  return regex.test(route);
}

const SUPPORTED_ROUTE_TYPES = new Set(SCHEMA_TYPES);

function pickSchemaType(pattern: string): SchemaType[] {
  const lower = pattern.toLowerCase();
  if (lower.includes('/search') || lower.includes('/buscar')) return ['PropertyListingPage', 'Offer', 'Place'];
  if (lower.includes('/map') || lower.includes('/mapa')) return ['Place'];
  if (lower.includes('/property/')) return ['PropertyListingPage', 'Offer', 'Place'];
  if (lower.includes('/faq') || lower.includes('/perguntas')) return ['FAQPage'];
  if (lower.includes('/how-to') || lower.includes('/como-funciona')) return ['HowTo'];
  if (lower.includes('/video')) return ['VideoObject'];
  return ['PropertyListingPage'];
}

function matchCoverage(rule: RouteRule): MatchResult {
  const types = rule.types.map((type) => `@type: ${type}`);
  return { route: rule.pattern, matched: true, types };
}

function computeCoverage(routes: RouteRule[]): MatchResult[] {
  return routes.map(matchCoverage);
}

function renderCoverage(matches: MatchResult[]): string {
  const total = matches.length;
  const matched = matches.filter((item) => item.matched).length;
  const coverage = total === 0 ? 0 : matched / total;

  const lines = [
    `# SEO Coverage`,
    ``,
    `- total routes: ${total}`,
    `- covered routes: ${matched}`,
    `- coverage: ${(coverage * 100).toFixed(2)}%`,
    ``,
    `| route | matched | supported types |`,
    `| --- | --- | --- |`,
    ...matches.map((item) => {
      const status = item.matched ? 'yes' : 'no';
      const types = item.types.join(', ');
      return `| \`${item.route}\` | ${status} | ${types} |`;
    }),
    ``,
    `Generated by @landmap/seo coverage CLI.`,
  ];

  return lines.join('\n');
}

function loadEnvSchema(envPath: string): Record<string, string> {
  if (!fs.existsSync(envPath)) return {};
  const raw = fs.readFileSync(envPath, 'utf8');
  const schema: Record<string, string> = {};

  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    schema[match[1]] = match[2].replace(/^["']|["']$/g, '');
  }

  return schema;
}

function buildN8nHook(envPath: string): string {
  const env = loadEnvSchema(envPath);

  return `[
  {
    "id": "seo-coverage",
    "name": "SEO schema coverage",
    "type": "hook",
    "enabled": true,
    "hooks": {
      "postRun": "/usr/bin/env --file-reference '${envPath}' npx --package @landmap/seo tsx --tsconfig tsconfig.esm.json packages/seo/src/cli/coverage.ts --routes packages/seo/src/cli/seo-routes.json"
    }
  }
]
`;
}

function writeOutput(outputPath: string, content: string): void {
  const absolute = path.resolve(outputPath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  fs.writeFileSync(absolute, content, 'utf8');
}

export function buildCoverage({ routes, output, format, n8n, env }: CoverageArgs): CoverageResult {
  const routesFile = String(routes ?? ROUTES_COLLECTION_FILE);
  const normalizedFormat = (format ?? 'md').toLowerCase() as string;
  const matches = computeCoverage(loadRoutes(routesFile));
  const coverage = matches.filter((item) => item.matched).length / matches.length;
  const result: CoverageResult = { matches, coverage };

  if (normalizedFormat === 'json') {
    const payload = JSON.stringify({ matches, coverage }, null, 2);
    if (output) {
      writeOutput(String(output), `${payload}\n`);
      result.output = `Coverage JSON written to ${path.resolve(String(output))}`;
      return result;
    }
    console.log(payload);
    return result;
  }

  if (normalizedFormat === 'html') {
    const html = [
      '<!doctype html>',
      '<html lang="en">',
      '<head><meta charset="utf-8"><title>SEO coverage</title></head>',
      '<body>',
      `<pre>${renderCoverage(matches)}</pre>`,
      '</body></html>',
    ].join('\n');

    if (output) {
      writeOutput(String(output), html);
      result.output = `Coverage HTML written to ${path.resolve(String(output))}`;
      return result;
    }

    console.log(html);
    return result;
  }

  const markdown = renderCoverage(matches);

  if (output) {
    writeOutput(String(output), markdown);
    result.output = `Coverage markdown written to ${path.resolve(String(output))}`;
    console.log(`coverage=${(coverage * 100).toFixed(2)}%`);

    if (n8n) {
      const envPath = String(env ?? '.env');
      const hook = buildN8nHook(envPath);
      console.log('--- n8n hook ---');
      console.log(hook);
      console.log(`Hook references ${envPath}.`);
    }

    return result;
  }

  console.log(markdown);

  if (n8n) {
    const envPath = String(env ?? '.env');
    const hook = buildN8nHook(envPath);
    console.log('--- n8n hook ---');
    console.log(hook);
    console.log(`Hook references ${envPath}.`);
  }

  return result;
}

function cli(): void {
  const {
    values,
    positionals,
  } = parseArgs({
    args: process.argv.slice(2),
    options: {
      routes: { type: 'string' },
      output: { type: 'string' },
      format: { type: 'string' },
      n8n: { type: 'boolean' },
      env: { type: 'string' },
      help: { type: 'boolean' },
    },
    allowPositionals: true,
  });

  if (values.help) {
    console.log(`@landmap/seo coverage CLI
Usage: coverage --routes <file> [--output <file>] [--format <md|json|html>]
       coverage --n8n --env <dotenv> [--routes <file>]

Required:
  --routes    Route rules file (JSON). Default: seo-routes.json

Optional:
  --output    Output file path. Default: stdout + coverage.json
  --format    Output format: md, json, html. Default: md
  --n8n       Generate n8n hook definition.
  --env       Dotenv file for n8n hook local execution.`);
    return;
  }

  buildCoverage({
    routes: String(values.routes ?? ROUTES_COLLECTION_FILE),
    output: String(values.output ?? ''),
    format: String(values.format ?? 'md').toLowerCase() as 'md' | 'json' | 'html',
    n8n: values.n8n ?? false,
    env: String(values.env ?? '.env'),
  });
}

cli();
