// LandMap — Supabase database types (mirrors supabase/migrations/0001_init.sql)
// Generated by hand to match the self-hosted Supabase schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      regions: {
        Row: {
          id: string;
          name: string;
          city: string;
          state: string;
          avg_observed_price_sqm: number;
          avg_announced_price_sqm: number | null;
          min_price: number | null;
          max_price: number | null;
          confidence: number;
          data_points: number;
          trend: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          city?: string;
          state?: string;
          avg_observed_price_sqm?: number;
          avg_announced_price_sqm?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          confidence?: number;
          data_points?: number;
          trend?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          city?: string;
          state?: string;
          avg_observed_price_sqm?: number;
          avg_announced_price_sqm?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          confidence?: number;
          data_points?: number;
          trend?: string | null;
          created_at?: string;
        };
      };
      region_favorites: {
        Row: { user_id: string; region_id: string; created_at: string };
        Insert: { user_id: string; region_id: string; created_at?: string };
        Update: { user_id?: string; region_id?: string; created_at?: string };
      };
      properties: {
        Row: {
          id: string;
          name: string | null;
          city: string | null;
          region_id: string | null;
          price: number | null;
          area_sqm: number | null;
          lat: number | null;
          lng: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name?: string | null;
          city?: string | null;
          region_id?: string | null;
          price?: number | null;
          area_sqm?: number | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          city?: string | null;
          region_id?: string | null;
          price?: number | null;
          area_sqm?: number | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
        };
      };
      property_favorites: {
        Row: { user_id: string; property_id: string; created_at: string };
        Insert: { user_id: string; property_id: string; created_at?: string };
        Update: { user_id?: string; property_id?: string; created_at?: string };
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          email: string | null;
          user_type: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          user_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          user_type?: string | null;
          created_at?: string;
        };
      };
      user_roles: {
        Row: { user_id: string; role: string; created_at: string };
        Insert: { user_id: string; role: string; created_at?: string };
        Update: { user_id?: string; role?: string; created_at?: string };
      };
      data_sources: {
        Row: {
          id: string;
          name: string;
          url: string | null;
          status: string | null;
          last_sync: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          url?: string | null;
          status?: string | null;
          last_sync?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          url?: string | null;
          status?: string | null;
          last_sync?: string | null;
          created_at?: string;
        };
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
}

export type Region = Database['public']['Tables']['regions']['Row'];
